 
version: "3.3"
services:
  server:
    container_name: "server"
    build: server
    ports:
      - "8080:4000"
    env_file: 
      - ./server/src/.env

  client:
    container_name: "client"
    build: client
    ports:
      - "3000:3000"
    links: 
      - server
    depends_on: 
      - server
    stdin_open: true
